# Generated by Django 5.0.6 on 2024-06-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='coach',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
