# Generated by Django 5.0.6 on 2024-06-14 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_drill_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drill',
            name='coach',
            field=models.ForeignKey(default=None, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
    ]
