# Generated by Django 5.0.6 on 2024-06-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_club_coach_alter_drill_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drill_on_training', to='training.drill'),
        ),
    ]
