# Generated by Django 5.0.6 on 2024-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_event_drill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='drill',
        ),
        migrations.AddField(
            model_name='event',
            name='drills',
            field=models.ManyToManyField(blank=True, null=True, related_name='drill_on_training', to='training.drill'),
        ),
    ]
