# Generated by Django 5.0.6 on 2024-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_event_drill_event_drills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_api_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='drills',
            field=models.ManyToManyField(blank=True, related_name='drill_on_training', to='training.drill'),
        ),
    ]
