# Generated by Django 5.0.6 on 2024-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_user_club_api_id_alter_event_drills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club_api_id',
        ),
        migrations.AddField(
            model_name='club',
            name='club_api_id',
            field=models.IntegerField(default=0),
        ),
    ]
