# Generated by Django 5.0.6 on 2024-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_remove_user_club_api_id_club_club_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_api_id',
            field=models.IntegerField(),
        ),
    ]
