# Generated by Django 5.0.6 on 2024-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_club_club_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='away_team_crest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='away_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_crest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_competition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Training', 'Training'), ('Recovery', 'Recovery'), ('Match', 'Match')], max_length=20),
        ),
    ]
