# Generated by Django 5.0.6 on 2024-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_rename_away_team_event_away_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_emblem',
            field=models.URLField(blank=True),
        ),
    ]
