# Generated by Django 5.0.6 on 2024-06-21 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_remove_event_date_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='coach',
            field=models.ForeignKey(default=None, limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        
    ]
