# Generated by Django 5.0.6 on 2024-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
