# Generated by Django 5.0.6 on 2024-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_alter_drill_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='away_team_crest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='away_team_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_team_crest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_team_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
