# Generated by Django 5.0.6 on 2024-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_alter_event_away_team_crest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
