# Generated by Django 5.0.6 on 2024-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_event_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='match_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
