# Generated by Django 5.0.6 on 2024-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_event_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.TextField(default=''),
        ),
    ]
