# Generated by Django 5.0.6 on 2024-07-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_user_dob_user_api_id_user_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DOB',
            new_name='DoB',
        ),
    ]
