# Generated by Django 5.0.6 on 2024-07-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_rename_dob_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='away_team_goals',
            new_name='away_team_goals_fulltime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='home_team_goals',
            new_name='home_team_goals_fulltime',
        ),
    ]
