# Generated by Django 5.0.6 on 2024-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_rename_away_team_goals_event_away_team_goals_fulltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team_goals_extratime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='away_team_goals_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_goals_extratime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_goals_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
