# Generated by Django 5.0.6 on 2024-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_event_away_team_goals_extratime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match_duration',
            field=models.CharField(default='REGULAR', max_length=100),
        ),
    ]
