# Generated by Django 5.0.6 on 2024-07-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_alter_event_match_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='match_duration',
        ),
    ]
