# Generated by Django 5.0.6 on 2024-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_remove_event_match_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='match_duration',
            field=models.CharField(default='REGULAR', max_length=100),
        ),
    ]
