# Generated by Django 5.0.6 on 2024-07-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_event_match_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='away_team_goals_extratime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_team_goals_extratime',
        ),
    ]
