# Generated by Django 5.0.6 on 2024-07-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_remove_event_away_team_goals_extratime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events2', to='training.calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='training.calendar'),
        ),
    ]
